/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as AuthenticatedAdminSuperRouteImport } from './routes/_authenticated/admin.super'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAdminEntregadoresRouteImport } from './routes/_authenticated/admin.entregadores'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCardapioRouteImport } from './routes/_authenticated/admin.cardapio'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSuperRoute = AuthenticatedAdminSuperRouteImport.update({
  id: '/admin/super',
  path: '/admin/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/admin/relatorios',
    path: '/admin/relatorios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/admin/onboarding',
    path: '/admin/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEntregadoresRoute =
  AuthenticatedAdminEntregadoresRouteImport.update({
    id: '/admin/entregadores',
    path: '/admin/entregadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/admin/cupons',
    path: '/admin/cupons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCardapioRoute =
  AuthenticatedAdminCardapioRouteImport.update({
    id: '/admin/cardapio',
    path: '/admin/cardapio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/admin/cardapio': typeof AuthenticatedAdminCardapioRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/super': typeof AuthenticatedAdminSuperRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/admin/cardapio': typeof AuthenticatedAdminCardapioRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/super': typeof AuthenticatedAdminSuperRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/_authenticated/admin/cardapio': typeof AuthenticatedAdminCardapioRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/super': typeof AuthenticatedAdminSuperRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/pedido/$orderId'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregadores'
    | '/admin/onboarding'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/super'
    | '/api/public/mercadopago-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/pedido/$orderId'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregadores'
    | '/admin/onboarding'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/super'
    | '/api/public/mercadopago-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/pedido/$orderId'
    | '/_authenticated/admin/cardapio'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/entregadores'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/super'
    | '/api/public/mercadopago-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/super': {
      id: '/_authenticated/admin/super'
      path: '/admin/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AuthenticatedAdminSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/entregadores': {
      id: '/_authenticated/admin/entregadores'
      path: '/admin/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AuthenticatedAdminEntregadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cardapio': {
      id: '/_authenticated/admin/cardapio'
      path: '/admin/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AuthenticatedAdminCardapioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminCardapioRoute: typeof AuthenticatedAdminCardapioRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminEntregadoresRoute: typeof AuthenticatedAdminEntregadoresRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminSuperRoute: typeof AuthenticatedAdminSuperRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminCardapioRoute: AuthenticatedAdminCardapioRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminEntregadoresRoute: AuthenticatedAdminEntregadoresRoute,
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminSuperRoute: AuthenticatedAdminSuperRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LojaSlugRoute: LojaSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
