/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CardapioDigitalRouteImport } from './routes/cardapio-digital'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlternativaIfoodRouteImport } from './routes/alternativa-ifood'
import { Route as SuperRouteImport } from './routes/_super'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SegmentosPizzariaRouteImport } from './routes/segmentos.pizzaria'
import { Route as SegmentosHamburgueriaRouteImport } from './routes/segmentos.hamburgueria'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ComparativoComandahubVsSaiposRouteImport } from './routes/comparativo.comandahub-vs-saipos'
import { Route as ComparativoComandahubVsGoomerRouteImport } from './routes/comparativo.comandahub-vs-goomer'
import { Route as ComparativoComandahubVsAnotaAiRouteImport } from './routes/comparativo.comandahub-vs-anota-ai'
import { Route as BlogSistemaDePedidosParaRestauranteRouteImport } from './routes/blog.sistema-de-pedidos-para-restaurante'
import { Route as BlogComoMontarCardapioDigitalCanvaVsPlataformaRouteImport } from './routes/blog.como-montar-cardapio-digital-canva-vs-plataforma'
import { Route as BlogComoFazerCardapioDigitalWhatsappRouteImport } from './routes/blog.como-fazer-cardapio-digital-whatsapp'
import { Route as BlogComoFazerCardapioDigitalGratisRouteImport } from './routes/blog.como-fazer-cardapio-digital-gratis'
import { Route as BlogComoCriarCardapioDigitalQrCodeRouteImport } from './routes/blog.como-criar-cardapio-digital-qr-code'
import { Route as SuperSuperIndexRouteImport } from './routes/_super/super.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublic_domainCheckRouteImport } from './routes/api/public/__domain-check'
import { Route as SuperSuperPlanosRouteImport } from './routes/_super/super.planos'
import { Route as SuperSuperLojasRouteImport } from './routes/_super/super.lojas'
import { Route as SuperSuperLeadsRouteImport } from './routes/_super/super.leads'
import { Route as SuperSuperEquipeRouteImport } from './routes/_super/super.equipe'
import { Route as SuperSuperConfiguracoesRouteImport } from './routes/_super/super.configuracoes'
import { Route as SuperSuperAvisosRouteImport } from './routes/_super/super.avisos'
import { Route as AuthenticatedAdminSuperRouteImport } from './routes/_authenticated/admin.super'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPdvRouteImport } from './routes/_authenticated/admin.pdv'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAdminEntregadoresRouteImport } from './routes/_authenticated/admin.entregadores'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCardapioRouteImport } from './routes/_authenticated/admin.cardapio'
import { Route as AuthenticatedAdminCaixaRouteImport } from './routes/_authenticated/admin.caixa'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioDigitalRoute = CardapioDigitalRouteImport.update({
  id: '/cardapio-digital',
  path: '/cardapio-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativaIfoodRoute = AlternativaIfoodRouteImport.update({
  id: '/alternativa-ifood',
  path: '/alternativa-ifood',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/_super',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosPizzariaRoute = SegmentosPizzariaRouteImport.update({
  id: '/segmentos/pizzaria',
  path: '/segmentos/pizzaria',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosHamburgueriaRoute = SegmentosHamburgueriaRouteImport.update({
  id: '/segmentos/hamburgueria',
  path: '/segmentos/hamburgueria',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativoComandahubVsSaiposRoute =
  ComparativoComandahubVsSaiposRouteImport.update({
    id: '/comparativo/comandahub-vs-saipos',
    path: '/comparativo/comandahub-vs-saipos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparativoComandahubVsGoomerRoute =
  ComparativoComandahubVsGoomerRouteImport.update({
    id: '/comparativo/comandahub-vs-goomer',
    path: '/comparativo/comandahub-vs-goomer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparativoComandahubVsAnotaAiRoute =
  ComparativoComandahubVsAnotaAiRouteImport.update({
    id: '/comparativo/comandahub-vs-anota-ai',
    path: '/comparativo/comandahub-vs-anota-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSistemaDePedidosParaRestauranteRoute =
  BlogSistemaDePedidosParaRestauranteRouteImport.update({
    id: '/blog/sistema-de-pedidos-para-restaurante',
    path: '/blog/sistema-de-pedidos-para-restaurante',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute =
  BlogComoMontarCardapioDigitalCanvaVsPlataformaRouteImport.update({
    id: '/blog/como-montar-cardapio-digital-canva-vs-plataforma',
    path: '/blog/como-montar-cardapio-digital-canva-vs-plataforma',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComoFazerCardapioDigitalWhatsappRoute =
  BlogComoFazerCardapioDigitalWhatsappRouteImport.update({
    id: '/blog/como-fazer-cardapio-digital-whatsapp',
    path: '/blog/como-fazer-cardapio-digital-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComoFazerCardapioDigitalGratisRoute =
  BlogComoFazerCardapioDigitalGratisRouteImport.update({
    id: '/blog/como-fazer-cardapio-digital-gratis',
    path: '/blog/como-fazer-cardapio-digital-gratis',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComoCriarCardapioDigitalQrCodeRoute =
  BlogComoCriarCardapioDigitalQrCodeRouteImport.update({
    id: '/blog/como-criar-cardapio-digital-qr-code',
    path: '/blog/como-criar-cardapio-digital-qr-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperSuperIndexRoute = SuperSuperIndexRouteImport.update({
  id: '/super/',
  path: '/super/',
  getParentRoute: () => SuperRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublic_domainCheckRoute = ApiPublic_domainCheckRouteImport.update({
  id: '/api/public/__domain-check',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperSuperPlanosRoute = SuperSuperPlanosRouteImport.update({
  id: '/super/planos',
  path: '/super/planos',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperLojasRoute = SuperSuperLojasRouteImport.update({
  id: '/super/lojas',
  path: '/super/lojas',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperLeadsRoute = SuperSuperLeadsRouteImport.update({
  id: '/super/leads',
  path: '/super/leads',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperEquipeRoute = SuperSuperEquipeRouteImport.update({
  id: '/super/equipe',
  path: '/super/equipe',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperConfiguracoesRoute = SuperSuperConfiguracoesRouteImport.update({
  id: '/super/configuracoes',
  path: '/super/configuracoes',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAvisosRoute = SuperSuperAvisosRouteImport.update({
  id: '/super/avisos',
  path: '/super/avisos',
  getParentRoute: () => SuperRoute,
} as any)
const AuthenticatedAdminSuperRoute = AuthenticatedAdminSuperRouteImport.update({
  id: '/admin/super',
  path: '/admin/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/admin/relatorios',
    path: '/admin/relatorios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPdvRoute = AuthenticatedAdminPdvRouteImport.update({
  id: '/admin/pdv',
  path: '/admin/pdv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/admin/onboarding',
    path: '/admin/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEntregadoresRoute =
  AuthenticatedAdminEntregadoresRouteImport.update({
    id: '/admin/entregadores',
    path: '/admin/entregadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/admin/cupons',
    path: '/admin/cupons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCardapioRoute =
  AuthenticatedAdminCardapioRouteImport.update({
    id: '/admin/cardapio',
    path: '/admin/cardapio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCaixaRoute = AuthenticatedAdminCaixaRouteImport.update({
  id: '/admin/caixa',
  path: '/admin/caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/alternativa-ifood': typeof AlternativaIfoodRoute
  '/auth': typeof AuthRoute
  '/cardapio-digital': typeof CardapioDigitalRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/blog/como-criar-cardapio-digital-qr-code': typeof BlogComoCriarCardapioDigitalQrCodeRoute
  '/blog/como-fazer-cardapio-digital-gratis': typeof BlogComoFazerCardapioDigitalGratisRoute
  '/blog/como-fazer-cardapio-digital-whatsapp': typeof BlogComoFazerCardapioDigitalWhatsappRoute
  '/blog/como-montar-cardapio-digital-canva-vs-plataforma': typeof BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute
  '/blog/sistema-de-pedidos-para-restaurante': typeof BlogSistemaDePedidosParaRestauranteRoute
  '/comparativo/comandahub-vs-anota-ai': typeof ComparativoComandahubVsAnotaAiRoute
  '/comparativo/comandahub-vs-goomer': typeof ComparativoComandahubVsGoomerRoute
  '/comparativo/comandahub-vs-saipos': typeof ComparativoComandahubVsSaiposRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/segmentos/hamburgueria': typeof SegmentosHamburgueriaRoute
  '/segmentos/pizzaria': typeof SegmentosPizzariaRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/caixa': typeof AuthenticatedAdminCaixaRoute
  '/admin/cardapio': typeof AuthenticatedAdminCardapioRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/super': typeof AuthenticatedAdminSuperRoute
  '/super/avisos': typeof SuperSuperAvisosRoute
  '/super/configuracoes': typeof SuperSuperConfiguracoesRoute
  '/super/equipe': typeof SuperSuperEquipeRoute
  '/super/leads': typeof SuperSuperLeadsRoute
  '/super/lojas': typeof SuperSuperLojasRoute
  '/super/planos': typeof SuperSuperPlanosRoute
  '/api/public': typeof ApiPublic_domainCheckRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super/': typeof SuperSuperIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/alternativa-ifood': typeof AlternativaIfoodRoute
  '/auth': typeof AuthRoute
  '/cardapio-digital': typeof CardapioDigitalRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/blog/como-criar-cardapio-digital-qr-code': typeof BlogComoCriarCardapioDigitalQrCodeRoute
  '/blog/como-fazer-cardapio-digital-gratis': typeof BlogComoFazerCardapioDigitalGratisRoute
  '/blog/como-fazer-cardapio-digital-whatsapp': typeof BlogComoFazerCardapioDigitalWhatsappRoute
  '/blog/como-montar-cardapio-digital-canva-vs-plataforma': typeof BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute
  '/blog/sistema-de-pedidos-para-restaurante': typeof BlogSistemaDePedidosParaRestauranteRoute
  '/comparativo/comandahub-vs-anota-ai': typeof ComparativoComandahubVsAnotaAiRoute
  '/comparativo/comandahub-vs-goomer': typeof ComparativoComandahubVsGoomerRoute
  '/comparativo/comandahub-vs-saipos': typeof ComparativoComandahubVsSaiposRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/segmentos/hamburgueria': typeof SegmentosHamburgueriaRoute
  '/segmentos/pizzaria': typeof SegmentosPizzariaRoute
  '/blog': typeof BlogIndexRoute
  '/admin/caixa': typeof AuthenticatedAdminCaixaRoute
  '/admin/cardapio': typeof AuthenticatedAdminCardapioRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/super': typeof AuthenticatedAdminSuperRoute
  '/super/avisos': typeof SuperSuperAvisosRoute
  '/super/configuracoes': typeof SuperSuperConfiguracoesRoute
  '/super/equipe': typeof SuperSuperEquipeRoute
  '/super/leads': typeof SuperSuperLeadsRoute
  '/super/lojas': typeof SuperSuperLojasRoute
  '/super/planos': typeof SuperSuperPlanosRoute
  '/api/public': typeof ApiPublic_domainCheckRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super': typeof SuperSuperIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_super': typeof SuperRouteWithChildren
  '/alternativa-ifood': typeof AlternativaIfoodRoute
  '/auth': typeof AuthRoute
  '/cardapio-digital': typeof CardapioDigitalRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/blog/como-criar-cardapio-digital-qr-code': typeof BlogComoCriarCardapioDigitalQrCodeRoute
  '/blog/como-fazer-cardapio-digital-gratis': typeof BlogComoFazerCardapioDigitalGratisRoute
  '/blog/como-fazer-cardapio-digital-whatsapp': typeof BlogComoFazerCardapioDigitalWhatsappRoute
  '/blog/como-montar-cardapio-digital-canva-vs-plataforma': typeof BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute
  '/blog/sistema-de-pedidos-para-restaurante': typeof BlogSistemaDePedidosParaRestauranteRoute
  '/comparativo/comandahub-vs-anota-ai': typeof ComparativoComandahubVsAnotaAiRoute
  '/comparativo/comandahub-vs-goomer': typeof ComparativoComandahubVsGoomerRoute
  '/comparativo/comandahub-vs-saipos': typeof ComparativoComandahubVsSaiposRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/segmentos/hamburgueria': typeof SegmentosHamburgueriaRoute
  '/segmentos/pizzaria': typeof SegmentosPizzariaRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/caixa': typeof AuthenticatedAdminCaixaRoute
  '/_authenticated/admin/cardapio': typeof AuthenticatedAdminCardapioRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/super': typeof AuthenticatedAdminSuperRoute
  '/_super/super/avisos': typeof SuperSuperAvisosRoute
  '/_super/super/configuracoes': typeof SuperSuperConfiguracoesRoute
  '/_super/super/equipe': typeof SuperSuperEquipeRoute
  '/_super/super/leads': typeof SuperSuperLeadsRoute
  '/_super/super/lojas': typeof SuperSuperLojasRoute
  '/_super/super/planos': typeof SuperSuperPlanosRoute
  '/api/public/__domain-check': typeof ApiPublic_domainCheckRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_super/super/': typeof SuperSuperIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/alternativa-ifood'
    | '/auth'
    | '/cardapio-digital'
    | '/contato'
    | '/empresa'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sla'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/blog/como-criar-cardapio-digital-qr-code'
    | '/blog/como-fazer-cardapio-digital-gratis'
    | '/blog/como-fazer-cardapio-digital-whatsapp'
    | '/blog/como-montar-cardapio-digital-canva-vs-plataforma'
    | '/blog/sistema-de-pedidos-para-restaurante'
    | '/comparativo/comandahub-vs-anota-ai'
    | '/comparativo/comandahub-vs-goomer'
    | '/comparativo/comandahub-vs-saipos'
    | '/email/unsubscribe'
    | '/loja/$slug'
    | '/pedido/$orderId'
    | '/segmentos/hamburgueria'
    | '/segmentos/pizzaria'
    | '/blog/'
    | '/admin/caixa'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregadores'
    | '/admin/onboarding'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/super'
    | '/super/avisos'
    | '/super/configuracoes'
    | '/super/equipe'
    | '/super/leads'
    | '/super/lojas'
    | '/super/planos'
    | '/api/public'
    | '/api/public/mercadopago-webhook'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/super/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/alternativa-ifood'
    | '/auth'
    | '/cardapio-digital'
    | '/contato'
    | '/empresa'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sla'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/blog/como-criar-cardapio-digital-qr-code'
    | '/blog/como-fazer-cardapio-digital-gratis'
    | '/blog/como-fazer-cardapio-digital-whatsapp'
    | '/blog/como-montar-cardapio-digital-canva-vs-plataforma'
    | '/blog/sistema-de-pedidos-para-restaurante'
    | '/comparativo/comandahub-vs-anota-ai'
    | '/comparativo/comandahub-vs-goomer'
    | '/comparativo/comandahub-vs-saipos'
    | '/email/unsubscribe'
    | '/loja/$slug'
    | '/pedido/$orderId'
    | '/segmentos/hamburgueria'
    | '/segmentos/pizzaria'
    | '/blog'
    | '/admin/caixa'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregadores'
    | '/admin/onboarding'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/super'
    | '/super/avisos'
    | '/super/configuracoes'
    | '/super/equipe'
    | '/super/leads'
    | '/super/lojas'
    | '/super/planos'
    | '/api/public'
    | '/api/public/mercadopago-webhook'
    | '/lovable/email/suppression'
    | '/admin'
    | '/super'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/_super'
    | '/alternativa-ifood'
    | '/auth'
    | '/cardapio-digital'
    | '/contato'
    | '/empresa'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sla'
    | '/sobre'
    | '/suporte'
    | '/termos'
    | '/blog/como-criar-cardapio-digital-qr-code'
    | '/blog/como-fazer-cardapio-digital-gratis'
    | '/blog/como-fazer-cardapio-digital-whatsapp'
    | '/blog/como-montar-cardapio-digital-canva-vs-plataforma'
    | '/blog/sistema-de-pedidos-para-restaurante'
    | '/comparativo/comandahub-vs-anota-ai'
    | '/comparativo/comandahub-vs-goomer'
    | '/comparativo/comandahub-vs-saipos'
    | '/email/unsubscribe'
    | '/loja/$slug'
    | '/pedido/$orderId'
    | '/segmentos/hamburgueria'
    | '/segmentos/pizzaria'
    | '/blog/'
    | '/_authenticated/admin/caixa'
    | '/_authenticated/admin/cardapio'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/entregadores'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/pdv'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/super'
    | '/_super/super/avisos'
    | '/_super/super/configuracoes'
    | '/_super/super/equipe'
    | '/_super/super/leads'
    | '/_super/super/lojas'
    | '/_super/super/planos'
    | '/api/public/__domain-check'
    | '/api/public/mercadopago-webhook'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_super/super/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
  AlternativaIfoodRoute: typeof AlternativaIfoodRoute
  AuthRoute: typeof AuthRoute
  CardapioDigitalRoute: typeof CardapioDigitalRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlaRoute: typeof SlaRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  BlogComoCriarCardapioDigitalQrCodeRoute: typeof BlogComoCriarCardapioDigitalQrCodeRoute
  BlogComoFazerCardapioDigitalGratisRoute: typeof BlogComoFazerCardapioDigitalGratisRoute
  BlogComoFazerCardapioDigitalWhatsappRoute: typeof BlogComoFazerCardapioDigitalWhatsappRoute
  BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute: typeof BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute
  BlogSistemaDePedidosParaRestauranteRoute: typeof BlogSistemaDePedidosParaRestauranteRoute
  ComparativoComandahubVsAnotaAiRoute: typeof ComparativoComandahubVsAnotaAiRoute
  ComparativoComandahubVsGoomerRoute: typeof ComparativoComandahubVsGoomerRoute
  ComparativoComandahubVsSaiposRoute: typeof ComparativoComandahubVsSaiposRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  SegmentosHamburgueriaRoute: typeof SegmentosHamburgueriaRoute
  SegmentosPizzariaRoute: typeof SegmentosPizzariaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublic_domainCheckRoute: typeof ApiPublic_domainCheckRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio-digital': {
      id: '/cardapio-digital'
      path: '/cardapio-digital'
      fullPath: '/cardapio-digital'
      preLoaderRoute: typeof CardapioDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternativa-ifood': {
      id: '/alternativa-ifood'
      path: '/alternativa-ifood'
      fullPath: '/alternativa-ifood'
      preLoaderRoute: typeof AlternativaIfoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super': {
      id: '/_super'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/pizzaria': {
      id: '/segmentos/pizzaria'
      path: '/segmentos/pizzaria'
      fullPath: '/segmentos/pizzaria'
      preLoaderRoute: typeof SegmentosPizzariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/hamburgueria': {
      id: '/segmentos/hamburgueria'
      path: '/segmentos/hamburgueria'
      fullPath: '/segmentos/hamburgueria'
      preLoaderRoute: typeof SegmentosHamburgueriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo/comandahub-vs-saipos': {
      id: '/comparativo/comandahub-vs-saipos'
      path: '/comparativo/comandahub-vs-saipos'
      fullPath: '/comparativo/comandahub-vs-saipos'
      preLoaderRoute: typeof ComparativoComandahubVsSaiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo/comandahub-vs-goomer': {
      id: '/comparativo/comandahub-vs-goomer'
      path: '/comparativo/comandahub-vs-goomer'
      fullPath: '/comparativo/comandahub-vs-goomer'
      preLoaderRoute: typeof ComparativoComandahubVsGoomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo/comandahub-vs-anota-ai': {
      id: '/comparativo/comandahub-vs-anota-ai'
      path: '/comparativo/comandahub-vs-anota-ai'
      fullPath: '/comparativo/comandahub-vs-anota-ai'
      preLoaderRoute: typeof ComparativoComandahubVsAnotaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/sistema-de-pedidos-para-restaurante': {
      id: '/blog/sistema-de-pedidos-para-restaurante'
      path: '/blog/sistema-de-pedidos-para-restaurante'
      fullPath: '/blog/sistema-de-pedidos-para-restaurante'
      preLoaderRoute: typeof BlogSistemaDePedidosParaRestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-montar-cardapio-digital-canva-vs-plataforma': {
      id: '/blog/como-montar-cardapio-digital-canva-vs-plataforma'
      path: '/blog/como-montar-cardapio-digital-canva-vs-plataforma'
      fullPath: '/blog/como-montar-cardapio-digital-canva-vs-plataforma'
      preLoaderRoute: typeof BlogComoMontarCardapioDigitalCanvaVsPlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-fazer-cardapio-digital-whatsapp': {
      id: '/blog/como-fazer-cardapio-digital-whatsapp'
      path: '/blog/como-fazer-cardapio-digital-whatsapp'
      fullPath: '/blog/como-fazer-cardapio-digital-whatsapp'
      preLoaderRoute: typeof BlogComoFazerCardapioDigitalWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-fazer-cardapio-digital-gratis': {
      id: '/blog/como-fazer-cardapio-digital-gratis'
      path: '/blog/como-fazer-cardapio-digital-gratis'
      fullPath: '/blog/como-fazer-cardapio-digital-gratis'
      preLoaderRoute: typeof BlogComoFazerCardapioDigitalGratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-criar-cardapio-digital-qr-code': {
      id: '/blog/como-criar-cardapio-digital-qr-code'
      path: '/blog/como-criar-cardapio-digital-qr-code'
      fullPath: '/blog/como-criar-cardapio-digital-qr-code'
      preLoaderRoute: typeof BlogComoCriarCardapioDigitalQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super/super/': {
      id: '/_super/super/'
      path: '/super'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperSuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/__domain-check': {
      id: '/api/public/__domain-check'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublic_domainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super/super/planos': {
      id: '/_super/super/planos'
      path: '/super/planos'
      fullPath: '/super/planos'
      preLoaderRoute: typeof SuperSuperPlanosRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super/lojas': {
      id: '/_super/super/lojas'
      path: '/super/lojas'
      fullPath: '/super/lojas'
      preLoaderRoute: typeof SuperSuperLojasRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super/leads': {
      id: '/_super/super/leads'
      path: '/super/leads'
      fullPath: '/super/leads'
      preLoaderRoute: typeof SuperSuperLeadsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super/equipe': {
      id: '/_super/super/equipe'
      path: '/super/equipe'
      fullPath: '/super/equipe'
      preLoaderRoute: typeof SuperSuperEquipeRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super/configuracoes': {
      id: '/_super/super/configuracoes'
      path: '/super/configuracoes'
      fullPath: '/super/configuracoes'
      preLoaderRoute: typeof SuperSuperConfiguracoesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super/avisos': {
      id: '/_super/super/avisos'
      path: '/super/avisos'
      fullPath: '/super/avisos'
      preLoaderRoute: typeof SuperSuperAvisosRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_authenticated/admin/super': {
      id: '/_authenticated/admin/super'
      path: '/admin/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AuthenticatedAdminSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pdv': {
      id: '/_authenticated/admin/pdv'
      path: '/admin/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AuthenticatedAdminPdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/entregadores': {
      id: '/_authenticated/admin/entregadores'
      path: '/admin/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AuthenticatedAdminEntregadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cardapio': {
      id: '/_authenticated/admin/cardapio'
      path: '/admin/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AuthenticatedAdminCardapioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/caixa': {
      id: '/_authenticated/admin/caixa'
      path: '/admin/caixa'
      fullPath: '/admin/caixa'
      preLoaderRoute: typeof AuthenticatedAdminCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminCaixaRoute: typeof AuthenticatedAdminCaixaRoute
  AuthenticatedAdminCardapioRoute: typeof AuthenticatedAdminCardapioRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminEntregadoresRoute: typeof AuthenticatedAdminEntregadoresRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminPdvRoute: typeof AuthenticatedAdminPdvRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminSuperRoute: typeof AuthenticatedAdminSuperRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminCaixaRoute: AuthenticatedAdminCaixaRoute,
  AuthenticatedAdminCardapioRoute: AuthenticatedAdminCardapioRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminEntregadoresRoute: AuthenticatedAdminEntregadoresRoute,
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminPdvRoute: AuthenticatedAdminPdvRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminSuperRoute: AuthenticatedAdminSuperRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SuperRouteChildren {
  SuperSuperAvisosRoute: typeof SuperSuperAvisosRoute
  SuperSuperConfiguracoesRoute: typeof SuperSuperConfiguracoesRoute
  SuperSuperEquipeRoute: typeof SuperSuperEquipeRoute
  SuperSuperLeadsRoute: typeof SuperSuperLeadsRoute
  SuperSuperLojasRoute: typeof SuperSuperLojasRoute
  SuperSuperPlanosRoute: typeof SuperSuperPlanosRoute
  SuperSuperIndexRoute: typeof SuperSuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperSuperAvisosRoute: SuperSuperAvisosRoute,
  SuperSuperConfiguracoesRoute: SuperSuperConfiguracoesRoute,
  SuperSuperEquipeRoute: SuperSuperEquipeRoute,
  SuperSuperLeadsRoute: SuperSuperLeadsRoute,
  SuperSuperLojasRoute: SuperSuperLojasRoute,
  SuperSuperPlanosRoute: SuperSuperPlanosRoute,
  SuperSuperIndexRoute: SuperSuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
  AlternativaIfoodRoute: AlternativaIfoodRoute,
  AuthRoute: AuthRoute,
  CardapioDigitalRoute: CardapioDigitalRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlaRoute: SlaRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  BlogComoCriarCardapioDigitalQrCodeRoute:
    BlogComoCriarCardapioDigitalQrCodeRoute,
  BlogComoFazerCardapioDigitalGratisRoute:
    BlogComoFazerCardapioDigitalGratisRoute,
  BlogComoFazerCardapioDigitalWhatsappRoute:
    BlogComoFazerCardapioDigitalWhatsappRoute,
  BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute:
    BlogComoMontarCardapioDigitalCanvaVsPlataformaRoute,
  BlogSistemaDePedidosParaRestauranteRoute:
    BlogSistemaDePedidosParaRestauranteRoute,
  ComparativoComandahubVsAnotaAiRoute: ComparativoComandahubVsAnotaAiRoute,
  ComparativoComandahubVsGoomerRoute: ComparativoComandahubVsGoomerRoute,
  ComparativoComandahubVsSaiposRoute: ComparativoComandahubVsSaiposRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LojaSlugRoute: LojaSlugRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  SegmentosHamburgueriaRoute: SegmentosHamburgueriaRoute,
  SegmentosPizzariaRoute: SegmentosPizzariaRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublic_domainCheckRoute: ApiPublic_domainCheckRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
